# Generated by Django 3.1.5 on 2021-02-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
