# Generated by Django 3.1.5 on 2021-02-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210220_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='527e5f7bc11b', max_length=255),
        ),
    ]
