# Generated by Django 3.1.5 on 2021-02-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210220_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='71cdcce6d486', max_length=255),
        ),
    ]
