# Generated by Django 3.1.5 on 2021-02-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20210220_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymembers',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='4cd063192bff', max_length=255),
        ),
    ]
