# Generated by Django 3.1.5 on 2021-02-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20210228_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='dae6a2d9aff9', max_length=255),
        ),
    ]
