# Generated by Django 3.1.5 on 2021-02-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20210220_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='32c10a5e5be5', max_length=255),
        ),
    ]
