# Generated by Django 3.1.5 on 2021-02-23 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20210220_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='738a04fc726a', max_length=255),
        ),
        migrations.CreateModel(
            name='AlergyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergen_name', models.CharField(default=None, max_length=100)),
                ('custom_alergen_input', models.CharField(default=None, max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='username_a', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
