# Generated by Django 3.1.5 on 2021-02-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20210228_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='c607da3c72ad', max_length=255),
        ),
    ]
