# Generated by Django 3.1.5 on 2021-02-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20210223_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='e2abf4df12a0', max_length=255),
        ),
    ]
