# Generated by Django 3.1.5 on 2021-02-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20210223_2053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlergyList',
            new_name='AllergyList',
        ),
        migrations.RenameField(
            model_name='allergylist',
            old_name='alergen_name',
            new_name='allergen_name',
        ),
        migrations.RenameField(
            model_name='allergylist',
            old_name='custom_alergen_input',
            new_name='custom_allergen_input',
        ),
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='450c8cfab05e', max_length=255),
        ),
    ]
