# Generated by Django 3.1.5 on 2021-02-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20210223_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergylist',
            name='allergen_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allergylist',
            name='custom_allergen_input',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='cc845c482af5', max_length=255),
        ),
    ]
