# Generated by Django 3.1.5 on 2021-02-28 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20210228_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslist',
            name='access_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='username_au', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='de3a88670b9e', max_length=255),
        ),
    ]
