# Generated by Django 3.1.5 on 2021-02-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20210223_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='3d30cd4fca99', max_length=255),
        ),
    ]
