# Generated by Django 3.1.5 on 2021-02-25 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20210223_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='69bf6e61fd89', max_length=255),
        ),
        migrations.CreateModel(
            name='RecognizedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded', models.BooleanField(default=True)),
                ('recognized', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='username_r', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
