# Generated by Django 3.1.5 on 2021-03-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20210228_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='1ebce41c0605', max_length=255),
        ),
    ]
