# Generated by Django 3.1.5 on 2021-02-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20210225_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='d0cf933e68e5', max_length=255),
        ),
    ]
