# Generated by Django 3.1.5 on 2021-02-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20210226_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='9a356098f583', max_length=255),
        ),
    ]
