# Generated by Django 3.1.5 on 2021-03-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20210312_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='8ec4cf67589f', max_length=255),
        ),
    ]
