# Generated by Django 3.1.5 on 2021-02-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20210226_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default="{% static 'portal/img/noimage.jpg' %}"),
        ),
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='3a02374ec23a', max_length=255),
        ),
    ]
