# Generated by Django 3.1.5 on 2021-02-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20210226_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='5399d056829e', max_length=255),
        ),
    ]
