# Generated by Django 3.1.5 on 2021-02-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20210226_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='b3a8cdb1e8e7', max_length=255),
        ),
    ]
