# Generated by Django 3.1.5 on 2021-03-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20210313_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='141c4ba62a06', max_length=255),
        ),
    ]
