# Generated by Django 3.1.5 on 2021-02-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20210226_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='4f7019a10456', max_length=255),
        ),
    ]
