# Generated by Django 3.1.5 on 2021-03-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20210313_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizedfiles',
            name='full_file_url',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='8bcc226aaff5', max_length=255),
        ),
    ]
