# Generated by Django 3.1.5 on 2021-02-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20210226_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/medicard-db.appspot.com/o/portal%2Fimg%2Fnoimage.jpg?alt=media&token=defb69c4-2ffc-4e10-be83-75498408c2e2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='6a95a2f65f7f', max_length=255),
        ),
    ]
