# Generated by Django 3.1.5 on 2021-03-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20210318_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='118889772fd1', max_length=255),
        ),
    ]
