# Generated by Django 3.1.5 on 2021-02-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20210226_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='short_info',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='bd45d6ba13bc', max_length=255),
        ),
    ]
