# Generated by Django 3.1.5 on 2021-02-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_auto_20210227_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='616fcfaf6981', max_length=255),
        ),
    ]
