# Generated by Django 3.1.5 on 2021-03-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_auto_20210318_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='703fe6ebad0a', max_length=255),
        ),
    ]
