# Generated by Django 3.1.5 on 2021-03-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_auto_20210318_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizedfiles',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='b882be82500c', max_length=255),
        ),
    ]
