# Generated by Django 3.1.5 on 2021-02-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_auto_20210227_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emergency_number',
            field=models.IntegerField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='home_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='b54c49cd4cdc', max_length=255),
        ),
    ]
