# Generated by Django 3.1.5 on 2021-03-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_auto_20210319_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='4ed32813eeb1', max_length=255),
        ),
    ]
