# Generated by Django 3.1.5 on 2021-02-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_auto_20210227_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='2b5240dbacd6', max_length=255),
        ),
    ]
