# Generated by Django 3.1.5 on 2021-02-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_auto_20210227_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.CharField(default='1920-01-01', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='ad1a19981029', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
