# Generated by Django 3.1.5 on 2021-02-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_auto_20210227_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='med_id',
            field=models.CharField(default='c36fd982600e', max_length=255),
        ),
    ]
